//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACDenkiRyokin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class denki_ryokin
    {
        public string ManagementID { get; set; }
        public string ChangeInfomation { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Applicant { get; set; }
        public string Status { get; set; }
    }
}
